version: "2"

services:

  #docker run --name some-guacd -d guacamole/guacd
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always
    networks:
      - default_net


  # docker run --name some-guacamole -p 8080:8080 guacamole/guacamole
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ${GUACPASSWORD}
      POSTGRES_USER: guacamole_user
    ports:
      - 8088:8080
    networks:
      - default_net


  postgres:
    image: postgres
    container_name: guac_postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ${GUACPASSWORD}
      POSTGRES_USER: guacamole_user
    volumes:
    #docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > initdb.sql 
    - ./init:/docker-entrypoint-initdb.d:ro
    - guac_volume:/var/lib/postgresql/data
    networks:
      - default_net


volumes:
  guac_volume:


networks:
  default_net:
    external: true      